name: CI Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libantlr4-runtime-dev python3 python3-pip g++ make

      - name: Install ANTLR Tool & Python deps
        run: |
          pip3 install --user pytest antlr4-tools
          # On ajoute le chemin des scripts python au PATH pour trouver 'antlr4'
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create config.mk for GitHub
        run: |
          # On demande à antlr4-tools où il a téléchargé le JAR complet
          ANTLR_COMPLETE_JAR=$(find $HOME/.antlr/lib -name "antlr-*-complete.jar" | head -n 1)
          
          echo "ANTLRJAR=$ANTLR_COMPLETE_JAR" > compiler/config.mk
          echo "ANTLRINC=/usr/include/antlr4-runtime/" >> compiler/config.mk
          echo "ANTLRLIB=/usr/lib/x86_64-linux-gnu/libantlr4-runtime.a" >> compiler/config.mk

      - name: Compile
        run: |
          # On force le téléchargement du JAR si pas encore là
          antlr4 | true 
          # On récupère le bon chemin du JAR pour le Makefile
          JAR_PATH=$(find $HOME/.antlr/lib -name "antlr-*-complete.jar" | head -n 1)
          sed -i "s|ANTLRJAR=.*|ANTLRJAR=$JAR_PATH|" compiler/config.mk
          
          make -C compiler

      - name: Run ifcc tests
        run: python3 ./ifcc-test.py testfiles